volumes:
  dropbox-home:

services:
  dropbox:
    hostname: ${HOSTNAME}
    build:
      context: dropbox
      args:
        USERACCOUNT: ${USERACCOUNT}
        GROUPACCOUNT: ${USERACCOUNT}
        UID: ${UID}
        GID: ${GID}
    volumes:
      - dropbox-home:/home/${USERACCOUNT}